name: 'Run benchmark'
inputs:
  scenario:
    description: 'The type of benchmark-scenario to execute ([Micro, Gradient, Baseline, Comparison])'
    required: false
    default: 'Micro'
  runtimes:
    description: 'The runtime version to use (e.g. netcoreapp31, net5.0)'
    required: false
    default: 'net5.0'
  exporters:
    description: 'The exporter(s) used for this run (GitHub/StackOverflow/RPlot/CSV/JSON/HTML/XML)'
    required: false
    default: fulljson rplot
  categories:
    description: 'An optional [--all|any] categories filter to apply'
    required: false
    default: ''
  execution-options:
    description: 'Any additional parameters passed to the benchmark'
    required: false
    default: ''
runs:
  using: "composite"
  steps:
    - name: Generating benchmark results (Micro)
      run: UnitsNet.Benchmark\Scripts\${{ inputs.scenario }} ${{ inputs.runtimes }} --exporters ${{ inputs.exporters }} ${{ inputs.categories }} ${{ inputs.execution-options }}
      shell: pwsh